In [1]:
import mysql.connector as sql
import pandas as pd
import datetime as dt
import numpy as np

In [2]:
db_connection = sql.connect(host='localhost', database='collection_users', user='pandas', password='password')
sbItems = pd.read_sql('SELECT * FROM UsersShoeboxItems', con=db_connection)
sbBundles = pd.read_sql('SELECT * FROM UsersShoeboxBundles', con=db_connection)
sbItemsRenditions = pd.read_sql('SELECT * FROM UsersShoeboxItemsRenditions', con=db_connection)

In [3]:
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_columns', 50)

# ShoeBoxItems

In [4]:
sbItems.head(50)

,id,user_id,action_id,tool_id,bundle_id,refers_to_id,refers_to_uid,fingerprint,title,description,secret,extension,mimetype,is_public,created,lastmodified,deleted,secret_o,extras,status_id,processed,input_id
0,789443,199,2,0,789383,0,0,e6c8ee7e3c4d75c6292befc26c24dc884db71cd4,,,UqbTQrnbo5BV,png,image/png,0,1412108184,1412109538,0,UqbTQrnbo5BV,,0,0,0
1,789513,199,2,0,789383,0,0,19260472a130fd3dce2671a3233cedf207729992,,,ARfJNtmR27n6,svg,image/svg+xml,0,1412109641,1412109641,0,ARfJNtmR27n6,,0,0,0
2,789969,231,1,0,789967,1,18706081,,,,,,type/prs.hyperlink,0,1412279952,1412286216,0,,,0,0,0
3,789989,231,1,0,789967,1,18771063,,,,,,type/prs.hyperlink,0,1412285074,1412286216,0,,,0,0,0
4,789991,231,1,0,789967,1,18630089,,,,,,type/prs.hyperlink,0,1412279981,1412286216,0,,,0,0,0
5,789993,231,1,0,789967,1,18731743,,,,,,type/prs.hyperlink,0,1412279981,1412286216,0,,,0,0,0
6,789995,231,1,0,789967,1,18549277,,,,,,type/prs.hyperlink,0,1412279981,1412286216,0,,,0,0,0
7,790373,247,2,8,790365,1,18731913,e612768311e890008508d5feb8cbdc2fda3167c4,,,qCt9zLY122sJ,obj,application/octet-stream,0,1412624073,1422677849,1422677849,qCt9zLY122sJ,,0,0,0
8,790375,247,1,0,790365,1,18464153,,,,,,type/prs.hyperlink,0,1412624073,1422677849,1422677849,,,0,0,0
9,790377,247,1,0,790365,1,18656317,,,,,,type/prs.hyperlink,0,1412624073,1422677849,1422677849,,,0,0,0
10,790383,247,1,0,790365,1,18658237,,,,,,type/prs.hyperlink,0,1412624168,1422677849,1422677849,,,0,0,0
11,790391,247,1,0,790365,1,18618039,,,,,,type/prs.hyperlink,0,1412624178,1422677849,1422677849,,,0,0,0
12,790405,247,1,0,790365,1,18481889,,,,,,type/prs.hyperlink,0,1412627947,1422677849,1422677849,,,0,0,0
13,790429,247,1,0,790365,1,18378529,,,,,,type/prs.hyperlink,0,1412627944,1422677850,1422677850,,,0,0,0
14,790431,247,2,8,790365,1,18402775,4f23b388bee89529dcbe4440ce4c30cc64786cbe,,,UvMiW2DqKt73,jpg,image/jpeg,0,1412628073,1422677850,1422677850,UvMiW2DqKt73,,0,0,0
15,790453,247,2,3,790365,1,18622423,c70d0985ff981241922a2e8dfc4bc90107135de2,,,XZZYrRBy6oH2,jpg,image/jpeg,0,1412629783,1422677850,1422677850,XZZYrRBy6oH2,,0,0,0
16,790469,247,2,0,790365,0,0,cf950b593499f7beddb94b860fe58ba1c5c66420,,,RF7JqqrUfypx,JPG,image/jpeg,0,1412630986,1422677850,1422677850,RF7JqqrUfypx,,0,0,0
17,790541,247,2,3,790365,1,18603565,5c6a200c93314b105ab587ffac2c08b893180441,,,TKr7AZ3Vki0x,jpg,image/jpeg,0,1412638477,1422677850,1422677850,TKr7AZ3Vki0x,,0,0,0
18,790555,247,2,0,790365,0,0,b0fd24507ab5332a5308b91d25379fdc4c1df1b5,,,xsansofVg4R0,jpg,image/jpg,0,1412638587,1422677851,1422677851,xsansofVg4R0,,0,0,0
19,790919,247,2,0,790917,0,0,cf950b593499f7beddb94b860fe58ba1c5c66420,,,NvesSW9txjn2,jpg,image/jpeg,0,1412717887,1422677851,1422677851,NvesSW9txjn2,,0,0,0
20,790923,247,2,0,790917,0,0,b0fd24507ab5332a5308b91d25379fdc4c1df1b5,,,EjS7iaxLbQDX,jpg,image/jpg,0,1412718191,1422677851,1422677851,EjS7iaxLbQDX,,0,0,0
21,790931,247,2,0,790917,0,0,bc75dfe32d0ad2cec9cd9891344582fe3a849a8f,,,CS8rb829fHD1,jpg,image/jpg,1,1412718512,1422677851,1422677851,CS8rb829fHD1,,0,0,0
22,790955,247,2,0,790917,0,0,710f6b6e1cca31c0d89889cb4e15bba42030e13e,,,jWJfm3qM8OiW,jpg,image/jpeg,1,1412721331,1422677851,1422677851,jWJfm3qM8OiW,,0,0,0
23,790957,247,2,0,790917,0,0,9477496650ea8bf273fc794f6a840bb26aadee36,,,yTY28XBWy15w,jpg,image/jpeg,1,1412721478,1422677852,1422677852,yTY28XBWy15w,,0,0,0
24,790961,247,2,0,790917,0,0,42a0ea09c9de95a7a713aae4161450b1c3a84838,,,jGk4mkNzJpRR,png,application/octet-stream,1,1412721538,1422677852,1422677852,jGk4mkNzJpRR,,0,0,0
25,790965,247,2,0,790917,0,0,5ea708312784a9436061ab69adafece5e9d30650,,,0AonCGspUHuy,jpg,image/jpeg,1,1412721653,1422677852,1422677852,0AonCGspUHuy,,0,0,0
26,790967,247,2,0,790917,0,0,202f06b0ff4279a35806afc10da12f8427463a68,,,ncPhbTsP7jFU,png,application/octet-stream,1,1412721703,1422677852,1422677852,ncPhbTsP7jFU,,0,0,0
27,796439,247,1,0,796435,1,18127219,,few James S. Sherman try down wealth,next George Bush yell back fuel,,,type/prs.hyperlink,1,1415049295,1422677847,1422677847,,,0,0,0
28,796499,247,2,0,796435,0,0,bc75dfe32d0ad2cec9cd9891344582fe3a849a8f,the king!,uploaded from OpenFrameworks,liSjE4JTnSaZ,jpg,image/jpg,1,1415050489,1422677847,1422677847,hyNMW5bsNPYQ,"{""fingerprints"":{""o"":{""sha1"":""bc75dfe32d0ad2ce...",0,0,0
29,797843,142,1,0,797837,1,18709977,,,,,,type/prs.hyperlink,0,1415133170,1415133364,0,,,0,0,0
30,797845,142,1,0,797837,1,18474311,,,,,,type/prs.hyperlink,0,1415133173,1415133364,0,,,0,0,0
31,798165,247,1,0,798159,1,18120815,,,,,,type/prs.hyperlink,0,1415149170,1422677845,1422677845,,,0,0,0
32,798249,247,1,0,798159,1,18484577,,different John Adams reach still achieve,good John C. Calhoun question really minister,,,type/prs.hyperlink,0,1415204575,1422677845,1422677845,,,0,0,0
33,798251,247,1,0,798159,1,18442041,,,,,,type/prs.hyperlink,0,1415204567,1422677845,1422677845,,,0,0,0
34,798253,247,1,0,798159,1,18650819,,,,,,type/prs.hyperlink,0,1415204581,1422677845,1422677845,,,0,0,0
35,798255,247,1,0,798159,1,18133457,,,,,,type/prs.hyperlink,0,1415204593,1422677845,1422677845,,,0,0,0
36,798701,247,2,8,798159,1,18481955,5ca5e6e6ea77288e90d5583caa9338c0c876231a,bad Ulysses S. Grant scatter there fuel,large Herbert Hoover leave as friction,M6sE4VWAjSOV,jpg,image/jpeg,1,1415217240,1422677845,1422677845,Oist2hB75s9G,"{""fingerprints"":{""o"":{""sha1"":""5ca5e6e6ea77288e...",0,0,0
37,798833,247,2,0,798159,0,0,7b9f90903aedae99fa25498da8852d1727e5998a,the king!,uploaded from OpenFrameworks,j8L6volyJeEL,jpg,image/jpg,1,1415222500,1422677846,1422677846,vaICBnW9Nunt,"{""fingerprints"":{""o"":{""sha1"":""7b9f90903aedae99...",0,0,0
38,798879,247,2,0,798159,0,0,2e06e0ec0c42b61f2704d69e3f005eee419ce690,test title,description2014-11-05-16-52-41-924,M68bEadMrKLa,obj,text/plain,1,1415224362,1422677846,1422677846,glnnP27TUky2,,0,0,0
39,798969,247,1,0,798159,1,18645407,,,,,,type/prs.hyperlink,0,1415147036,1422677846,1422677846,,,0,0,0
40,798971,247,1,0,798159,1,18804677,,,,,,type/prs.hyperlink,0,1415147036,1422677847,1422677847,,,0,0,0
41,798973,247,1,0,798159,1,18728265,,,,,,type/prs.hyperlink,0,1415147036,1422677847,1422677847,,,0,0,0
42,799045,247,1,0,798159,1,18492083,,,,,,type/prs.hyperlink,0,1415230680,1422677847,1422677847,,,0,0,0
43,799047,247,1,0,798159,1,18193699,,,,,,type/prs.hyperlink,0,1415230680,1422677847,1422677847,,,0,0,0
44,799049,247,1,0,798159,1,18122837,,,,,,type/prs.hyperlink,0,1415230680,1422677847,1422677847,,,0,0,0
45,799051,247,1,0,798159,1,18803591,,,,,,type/prs.hyperlink,0,1415230680,1422677847,1422677847,,,0,0,0
46,799055,247,1,0,798159,1,18133385,,,,,,type/prs.hyperlink,0,1415230701,1422677847,1422677847,,,0,0,0
47,799059,247,1,0,798159,1,18319405,,,,,,type/prs.hyperlink,0,1415230701,1422677847,1422677847,,,0,0,0
48,799061,247,1,0,798159,1,18111691,,,,,,type/prs.hyperlink,0,1415230701,1422677847,1422677847,,,0,0,0
49,799065,247,1,0,798159,1,18686053,,,,,,type/prs.hyperlink,0,1415230701,1422677848,1422677848,,,0,0,0

In [5]:
sbItems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555921 entries, 0 to 1555920
Data columns (total 22 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   id             1555921 non-null  int64
 1   user_id        1555921 non-null  int64
 2   action_id      1555921 non-null  int64
 3   tool_id        1555921 non-null  int64
 4   bundle_id      1555921 non-null  int64
 5   refers_to_id   1555921 non-null  int64
 6   refers_to_uid  1555921 non-null  int64
 7   fingerprint    1555921 non-null  object
 8   title          1555921 non-null  object
 9   description    1555921 non-null  object
 10  secret         1555921 non-null  object
 11  extension      1555921 non-null  object
 12  mimetype       1555921 non-null  object
 13  is_public      1555921 non-null  int64
 14  created        1555921 non-null  int64
 15  lastmodified   1555921 non-null  int64
 16  deleted        1555921 non-null  int64
 17  secret_o       1555921 non-null  object
 18  extras         1555921 non-null  object
 19  status_id      1555921 non-null  int64
 20  processed      1555921 non-null  int64
 21  input_id       1555921 non-null  int64
dtypes: int64(14), object(8)
memory usage: 261.2+ MB

In [6]:
sbItems.shape

(1555921, 22)

In [7]:
sbItems.nunique()

id               1555921
user_id            23681
action_id              2
tool_id               15
bundle_id          22589
refers_to_id           6
refers_to_uid      75428
fingerprint        20911
title               1973
description          394
secret             22753
extension              7
mimetype              10
is_public              2
created           955050
lastmodified      211013
deleted            15852
secret_o           22753
extras             21552
status_id              3
processed           1050
input_id               4
dtype: int64

In [8]:
sbItems['tool_id'] = sbItems['tool_id'].astype('category')
sbItems['extension'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)
sbItems['extension'] = sbItems['extension'].astype('category')
sbItems['mimetype'] = sbItems['mimetype'].astype('category')
sbItems['created'] = pd.to_datetime(sbItems['created'], unit='s')
sbItems['lastmodified'] = pd.to_datetime(sbItems['lastmodified'], unit='s')
sbItems['deleted'].replace(0, np.nan, inplace=True)
sbItems['deleted'] = pd.to_datetime(sbItems['deleted'], unit='s')
sbItems['refers_to_uid'].replace(0, np.nan, inplace=True)
sbItems['fingerprint'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)
sbItems['title'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)
sbItems['description'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)
sbItems['secret'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)
sbItems['secret_o'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)
sbItems['extras'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)

In [9]:
sbItems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555921 entries, 0 to 1555920
Data columns (total 22 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   id             1555921 non-null  int64
 1   user_id        1555921 non-null  int64
 2   action_id      1555921 non-null  int64
 3   tool_id        1555921 non-null  category
 4   bundle_id      1555921 non-null  int64
 5   refers_to_id   1555921 non-null  int64
 6   refers_to_uid  1555184 non-null  float64
 7   fingerprint    22752 non-null    object
 8   title          25204 non-null    object
 9   description    22639 non-null    object
 10  secret         22752 non-null    object
 11  extension      22752 non-null    category
 12  mimetype       1555921 non-null  category
 13  is_public      1555921 non-null  int64
 14  created        1555921 non-null  datetime64[ns]
 15  lastmodified   1555921 non-null  datetime64[ns]
 16  deleted        18505 non-null    datetime64[ns]
 17  secret_o       22752 non-null    object
 18  extras         22300 non-null    object
 19  status_id      1555921 non-null  int64
 20  processed      1555921 non-null  int64
 21  input_id       1555921 non-null  int64
dtypes: category(3), datetime64[ns](3), float64(1), int64(9), object(6)
memory usage: 230.0+ MB

In [10]:
sbItems.drop(['status_id', 'processed', 'input_id'], axis=1, inplace=True)

In [26]:
sbItems.sample(10)
##what the different between the id?? the first id is what?
#how to inquiry the img / fingerprints/ bundles. is it a way in the website api?

,id,user_id,action_id,tool_id,bundle_id,refers_to_id,refers_to_uid,fingerprint,title,description,secret,extension,mimetype,is_public,created,lastmodified,deleted,secret_o,extras
450368,92140493,2915,1,0,92135179,1,136252337.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2016-01-04 21:51:26,2016-01-06 08:23:19,NaT,NaN,NaN
158334,85899275,3348,1,0,85887757,1,18645595.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2015-07-03 15:44:40,2015-07-04 01:03:04,NaT,NaN,NaN
1063742,109044439,16219,1,0,109040251,1,18218907.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2016-09-27 17:35:02,2016-09-30 20:33:47,NaT,NaN,NaN
1064458,109069657,16193,1,0,109065533,1,404529595.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,1,2016-09-28 18:45:54,2016-09-28 21:28:34,NaT,NaN,NaN
1154722,113483977,18782,1,0,113478565,1,420556719.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2017-04-08 18:05:04,2017-04-08 20:21:53,NaT,NaN,NaN
1189874,114490683,19355,1,0,114482871,1,420577305.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2017-05-02 16:38:38,2017-05-06 14:50:26,NaT,NaN,NaN
337819,89411333,6565,1,0,89408275,1,136253137.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2015-10-24 17:06:18,2015-10-26 15:14:53,NaT,NaN,NaN
1146258,112988177,18634,1,0,112984717,1,18621833.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2017-03-11 21:44:02,2017-03-23 22:44:53,NaT,NaN,NaN
601764,95441275,10800,1,0,95421663,1,219777443.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,1,2016-03-13 19:06:51,2016-03-15 01:54:54,NaT,NaN,NaN
606822,95537353,10887,1,0,95537271,1,69172085.0,NaN,NaN,NaN,NaN,NaN,type/prs.hyperlink,0,2016-03-15 19:46:35,2016-03-17 23:18:35,NaT,NaN,NaN

# ShoeBoxBundles

In [12]:
sbBundles.head(50)

,id,user_id,type_id,title,description,is_public,created,lastmodified,deleted,count_items,count_items_public,exported
0,789383,199,1,"Your visit to the museum on September 30, 2014",,0,1412097859,1427925740,0,3,0,0
1,789967,231,1,"Your visit to the museum on October 2, 2014",,0,1412279952,1427925740,0,5,0,0
2,790365,247,1,"Your visit to the museum on October 6, 2014",,0,1412624073,1427925740,1422677849,0,0,0
3,790917,247,1,"Your visit to the museum on October 7, 2014",,0,1412717887,1427925740,1422677851,0,0,0
4,796435,247,1,"Your visit to the museum on November 3, 2014",,0,1415050345,1427925740,1422677847,0,0,0
5,797837,142,1,"Your visit to the museum on November 4, 2014",,0,1415133364,1427925740,0,2,0,0
6,798159,247,1,"Your visit to the museum on November 4, 2014",,0,1415229391,1427925740,1422677845,0,0,0
7,1511605,9878,1,"Your visit to the museum on December 19, 2014",,0,1456079144,1456079151,0,30,0,0
8,1513173,247,1,"Your visit to the museum on January 6, 2015",,0,1420579768,1427925740,1422677842,0,0,0
9,1513947,158,1,"Your visit to the museum on January 7, 2015",,0,1421783770,1474167676,0,70,0,0
10,1516547,247,1,"Your visit to the museum on January 21, 2015",,0,1422918973,1427925740,0,7,0,0
11,1517519,377,1,"Your visit to the museum on January 26, 2015",,0,1422302527,1427925740,0,5,0,0
12,1517565,377,1,"Your visit to the museum on January 26, 2015",,0,1422304782,1427925740,0,6,0,0
13,1517579,377,1,"Your visit to the museum on January 26, 2015",,0,1422305175,1427925740,0,5,0,0
14,1517595,377,1,"Your visit to the museum on January 26, 2015",,0,1422305801,1427925740,0,3,0,0
15,1517605,377,1,"Your visit to the museum on January 26, 2015",,0,1422306532,1427925740,0,3,0,0
16,1517619,377,1,"Your visit to the museum on January 26, 2015",,0,1422307005,1427925740,0,2,0,0
17,1519683,142,1,"Your visit to the museum on February 3, 2015",,0,1422988852,1427925740,0,10,0,0
18,1526653,247,1,"Your visit to the museum on December 31, 1969",,0,1423172966,1427925740,0,0,0,0
19,1526919,247,1,"Your visit to the museum on December 31, 1969",,0,1423236880,1428426651,0,36,0,0
20,1583787,158,1,"Your visit to the museum on February 23, 2015",,0,1424990220,1427925740,0,10,0,0
21,1585363,247,1,"Your visit to the museum on February 24, 2015",,0,1424794440,1427925740,0,2,0,0
22,1585563,158,1,"Your visit to the museum on February 24, 2015",,0,1424990047,1427925740,0,15,0,0
23,1585591,3,1,"Your visit to the museum on February 24, 2015",,0,1424802550,1427925740,1424804752,0,0,0
24,1586155,247,1,"Your visit to the museum on February 25, 2015",,0,1424879050,1592850559,0,2534,0,0
25,1643091,247,1,"Your visit to the museum on February 26, 2015",,0,1425402528,1427925740,0,11,0,0
26,1643249,3,1,"Your visit to the museum on December 31, 1969",,0,1424988881,1432312960,0,37,0,1432048269
27,1644191,247,1,"Your visit to the museum on February 27, 2015",,0,1425054603,1427925740,0,3,0,0
28,1644669,686,1,"Your visit to the museum on December 31, 1969",,0,1426945533,1427925741,0,15,0,0
29,1645843,247,1,"Your visit to the museum on March 4, 2015",,0,1425497247,1427925741,0,26,0,0
30,1652095,426,1,"Your visit to the museum on December 31, 1969",,0,1425575257,1427925741,0,24,0,0
31,1652495,395,1,"Your visit to the museum on December 31, 1969",,0,1425582928,1431968491,0,36,2,0
32,1652511,431,1,"Your visit to the museum on December 31, 1969",,0,1425656756,1431968491,0,36,0,0
33,1652515,142,1,"Your visit to the museum on December 31, 1969",,0,1425588131,1428426653,0,36,0,0
34,1652527,437,1,"Your visit to the museum on December 31, 1969",,0,1425944697,1428426654,0,6,0,0
35,1652539,429,1,"Your visit to the museum on December 31, 1969",,0,1425586492,1428426653,0,36,1,0
36,1684491,247,1,"Your visit to the museum on March 5, 2015",,0,1425600474,1427925741,0,8,0,0
37,1684809,247,1,"Your visit to the museum on March 6, 2015",,0,1425654800,1427925741,0,36,1,0
38,1788509,3,1,"Your visit to the museum on March 6, 2015",,0,1425715337,1432067708,0,1,0,1431361748
39,2713403,247,1,"Your visit to the museum on March 7, 2015",,0,1425750814,1427925741,0,8,0,0
40,2927645,247,1,"Your visit to the museum on March 8, 2015",,0,1425833624,1427925741,0,13,0,0
41,3085357,438,1,"Your visit to the museum on March 9, 2015",,0,1425953128,1427925741,0,19,0,0
42,3085359,433,1,"Your visit to the museum on March 9, 2015",,0,1425911732,1427925741,0,13,0,0
43,3085371,435,1,"Your visit to the museum on March 9, 2015",,0,1425914638,1428426654,0,36,19,0
44,3085391,547,1,"Your visit to the museum on March 9, 2015",,0,1427559389,1427925741,0,15,13,0
45,3085397,395,1,"Your visit to the museum on March 9, 2015",,1,1425910472,1455804101,0,14,14,1432128902
46,3085415,434,1,"Your visit to the museum on March 9, 2015",,0,1425912329,1428426654,0,23,0,0
47,3085421,247,1,"Your visit to the museum on March 9, 2015",,0,1425901715,1427925741,0,12,1,0
48,3094545,445,1,"Your visit to the museum on March 10, 2015",,0,1426019610,1427925741,0,27,0,0
49,3094715,451,1,"Your visit to the museum on March 10, 2015",,0,1426044822,1428426654,0,36,0,0

In [13]:
sbBundles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23126 entries, 0 to 23125
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  23126 non-null  int64
 1   user_id             23126 non-null  int64
 2   type_id             23126 non-null  int64
 3   title               23126 non-null  object
 4   description         23126 non-null  object
 5   is_public           23126 non-null  int64
 6   created             23126 non-null  int64
 7   lastmodified        23126 non-null  int64
 8   deleted             23126 non-null  int64
 9   count_items         23126 non-null  int64
 10  count_items_public  23126 non-null  int64
 11  exported            23126 non-null  int64
dtypes: int64(10), object(2)
memory usage: 2.1+ MB

In [14]:
sbBundles['created'] = pd.to_datetime(sbBundles['created'], unit='s')
sbBundles['lastmodified'] = pd.to_datetime(sbBundles['lastmodified'], unit='s')
sbBundles['deleted'].replace(0, np.nan, inplace=True)
sbBundles['deleted'] = pd.to_datetime(sbBundles['deleted'], unit='s')
sbBundles['description'].replace(r'^\s*$', np.NaN, regex=True, inplace=True)

In [15]:
sbBundles.sample()
#what is the different between count_items. and count_items_public?
#id here is id_bundle is assume

,id,user_id,type_id,title,description,is_public,created,lastmodified,deleted,count_items,count_items_public,exported
2436,85340237,2988,1,"Your visit to the museum on June 10, 2015",NaN,0,2015-06-16 02:34:57,2015-06-16 02:35:00,NaT,31,0,0

# ShoeboxItemsRenditions

In [16]:
sbItemsRenditions.shape

(20823, 13)

In [17]:
sbItemsRenditions.nunique()

id              20823
source_id       20823
size                1
user_id          7021
fingerprint     20118
secret          20823
extension           4
mimetype            4
created         20816
lastmodified    18723
deleted             1
secret_o        20823
bundle_id        7437
dtype: int64

In [18]:
sbItemsRenditions

,id,source_id,size,user_id,fingerprint,secret,extension,mimetype,created,lastmodified,deleted,secret_o,bundle_id
0,793425,793423,o,3,cf950b593499f7beddb94b860fe58ba1c5c66420,993a58ab9ef5,jpg,image/jpeg,1414079320,1414080819,0,wvbkvD5bGLEq,0
1,793431,793429,o,3,485f83e02e6298268b1dcd9b3bf42bb902e40a0b,00114d3874d8,jpg,image/jpeg,1414079725,1414080818,0,OaKG4KMp9ZX1,0
2,793443,793441,o,3,9300eae08eac53aaf50f49e3e794f2e6e0947833,ef7a4bee918a,png,image/png,1414080712,1414080817,0,DpTA3c3JPhBr,0
3,794987,794985,o,305,21b1ef07e0b248d118a93560bb7051822c7103ad,4f09eac38cd3,png,image/png,1414617158,1414617236,0,HnZDtY6mL5Ak,0
4,798839,798837,o,247,2e06e0ec0c42b61f2704d69e3f005eee419ce690,668be91e7fc3,obj,image/jpg,1415222737,1415229393,0,TnxBW0FTumxy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20818,132873407,132873405,o,28814,81a8e64e80ae2e39e4aad7cd752f70361885546f,5cbd50cb13ac,png,image/png,1595449504,1595449583,0,OUXEgjbQZwXd,132777661
20819,132873411,132873409,o,28814,b12d3a36ddf17104ff13149cde8c020eac79a285,eeea537bcbad,png,image/png,1595449610,1595449611,0,ir4TwqoGw4Sk,132777661
20820,132873415,132873413,o,28814,07f206dd7674bbeaa6325e8b66c9eeada995399c,dc050ea74a67,png,image/png,1595449666,1595449667,0,Y3TtqFH6Y7Wd,132777661
20821,132873419,132873417,o,28814,de7d62a819f021b327f09523226558b19203673e,061727f4910e,png,image/png,1595450275,1595450275,0,f7Lv1Mba0L2T,132777661
20822,132873429,132873427,o,28814,f13e6ba9d097792a2cb8216d6ed754d55ff24dbf,d48d17ded441,png,image/png,1595451289,1595451289,0,EpnPXN2lT6P8,132777661

In [19]:
sbItemsRenditions['created'] = pd.to_datetime(sbItemsRenditions['created'], unit='s')
sbItemsRenditions['lastmodified'] = pd.to_datetime(sbItemsRenditions['lastmodified'], unit='s')
sbItemsRenditions['deleted'].replace(0, np.nan, inplace=True)
sbItemsRenditions['deleted'] = pd.to_datetime(sbItemsRenditions['deleted'], unit='s')
sbItemsRenditions['extension'] = sbItemsRenditions['extension'].astype('category')
sbItemsRenditions['mimetype'] = sbItemsRenditions['mimetype'].astype('category')
sbItemsRenditions['size'].replace('o', np.NaN, inplace=True)

In [22]:
sbItemsRenditions.nunique()

id              20823
source_id       20823
size                0
user_id          7021
fingerprint     20118
secret          20823
extension           4
mimetype            4
created         20816
lastmodified    18723
deleted             0
secret_o        20823
bundle_id        7437
dtype: int64

In [23]:
sbItemsRenditions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20823 entries, 0 to 20822
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20823 non-null  int64
 1   source_id     20823 non-null  int64
 2   size          0 non-null      float64
 3   user_id       20823 non-null  int64
 4   fingerprint   20823 non-null  object
 5   secret        20823 non-null  object
 6   extension     20823 non-null  category
 7   mimetype      20823 non-null  category
 8   created       20823 non-null  datetime64[ns]
 9   lastmodified  20823 non-null  datetime64[ns]
 10  deleted       0 non-null      datetime64[ns]
 11  secret_o      20823 non-null  object
 12  bundle_id     20823 non-null  int64
dtypes: category(2), datetime64[ns](3), float64(1), int64(4), object(3)
memory usage: 1.8+ MB

In [24]:
sbItemsRenditions.sample()
#source id?

,id,source_id,size,user_id,fingerprint,secret,extension,mimetype,created,lastmodified,deleted,secret_o,bundle_id
8982,92704453,92704451,NaN,9327,bc24843d1aa6e47f88a4aa8f9c428e933fe81b9a,d1a409e4f654,png,image/png,2016-01-22 18:31:26,2016-02-02 14:04:12,NaT,mzlhZHYWchBW,92701317